-- MySQL Script generated by MySQL Workbench
-- mar 22 may 2018 18:41:57 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema apimultas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema apimultas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apimultas` DEFAULT CHARACTER SET utf8 ;
USE `apimultas` ;

-- -----------------------------------------------------
-- Table `apimultas`.`datos_vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apimultas`.`datos_vehiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `no_multa` BIGINT(20) UNSIGNED NOT NULL,
  `no_placa` VARCHAR(20) NOT NULL,
  `no_tarjeta_cir` VARCHAR(40) NOT NULL,
  `tipo_vehiculo` VARCHAR(40) NOT NULL,
  `marca` VARCHAR(40) NOT NULL,
  `color` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `no_placa_UNIQUE` (`no_placa` ASC),
  UNIQUE INDEX `no_multa_UNIQUE` (`no_multa` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apimultas`.`datos_infractor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apimultas`.`datos_infractor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(60) NOT NULL,
  `apellidos` VARCHAR(60) NOT NULL,
  `conductor_ausente` VARCHAR(120) NOT NULL,
  `genero` VARCHAR(15) NOT NULL,
  `no_licencia` VARCHAR(16) NOT NULL,
  `tipo_licencia` VARCHAR(5) NOT NULL,
  `no_documento_dpi` VARCHAR(16) NOT NULL,
  `domicilio` VARCHAR(120) NOT NULL,
  `datos_vehiculo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_datos_infractor_datos_vehiculo_idx` (`datos_vehiculo_id` ASC),
  CONSTRAINT `fk_datos_infractor_datos_vehiculo`
    FOREIGN KEY (`datos_vehiculo_id`)
    REFERENCES `apimultas`.`datos_vehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apimultas`.`datos_infraccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apimultas`.`datos_infraccion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lugar_infraccion` TEXT(250) NOT NULL,
  `municipio_infraccion` VARCHAR(15) NOT NULL,
  `fecha_infraccion` DATE NOT NULL,
  `hora_infraccion` TIME NOT NULL,
  `datos_vehiculo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_datos_infraccion_datos_vehiculo1_idx` (`datos_vehiculo_id` ASC),
  CONSTRAINT `fk_datos_infraccion_datos_vehiculo1`
    FOREIGN KEY (`datos_vehiculo_id`)
    REFERENCES `apimultas`.`datos_vehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apimultas`.`articulo_infringido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apimultas`.`articulo_infringido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `no_articulo` INT UNSIGNED NOT NULL,
  `descripcion_articulo` TEXT(240) NOT NULL,
  `base_legal` TEXT(240) NOT NULL,
  `monto_infraccion` DECIMAL UNSIGNED NOT NULL,
  `datos_vehiculo_id` INT NOT NULL,
  `datos_infraccion_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_articulo_infringido_datos_vehiculo1_idx` (`datos_vehiculo_id` ASC),
  INDEX `fk_articulo_infringido_datos_infraccion1_idx` (`datos_infraccion_id` ASC),
  CONSTRAINT `fk_articulo_infringido_datos_vehiculo1`
    FOREIGN KEY (`datos_vehiculo_id`)
    REFERENCES `apimultas`.`datos_vehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articulo_infringido_datos_infraccion1`
    FOREIGN KEY (`datos_infraccion_id`)
    REFERENCES `apimultas`.`datos_infraccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apimultas`.`datos_agente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apimultas`.`datos_agente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `no_identificacion` VARCHAR(60) NOT NULL,
  `firmo_agente` TINYINT(1) NOT NULL,
  `firmo_infractor` TINYINT(1) NULL,
  `nego_firmar_infractor` TINYINT(1) NULL,
  `datos_vehiculo_id` INT NOT NULL,
  `articulo_infringido_id` INT NOT NULL,
  `datos_infraccion_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_datos_agente_datos_vehiculo1_idx` (`datos_vehiculo_id` ASC),
  INDEX `fk_datos_agente_articulo_infringido1_idx` (`articulo_infringido_id` ASC),
  INDEX `fk_datos_agente_datos_infraccion1_idx` (`datos_infraccion_id` ASC),
  CONSTRAINT `fk_datos_agente_datos_vehiculo1`
    FOREIGN KEY (`datos_vehiculo_id`)
    REFERENCES `apimultas`.`datos_vehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_datos_agente_articulo_infringido1`
    FOREIGN KEY (`articulo_infringido_id`)
    REFERENCES `apimultas`.`articulo_infringido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_datos_agente_datos_infraccion1`
    FOREIGN KEY (`datos_infraccion_id`)
    REFERENCES `apimultas`.`datos_infraccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apimultas`.`observaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apimultas`.`observaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `observacion` TEXT(240) NULL,
  `datos_agente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_observaciones_datos_agente1_idx` (`datos_agente_id` ASC),
  CONSTRAINT `fk_observaciones_datos_agente1`
    FOREIGN KEY (`datos_agente_id`)
    REFERENCES `apimultas`.`datos_agente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apimultas`.`privilegios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apimultas`.`privilegios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `privilegio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `privilegio_UNIQUE` (`privilegio` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apimultas`.`credenciales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apimultas`.`credenciales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `privilegios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_credenciales_privilegios1_idx` (`privilegios_id` ASC),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC),
  CONSTRAINT `fk_credenciales_privilegios1`
    FOREIGN KEY (`privilegios_id`)
    REFERENCES `apimultas`.`privilegios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apimultas`.`placa_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apimultas`.`placa_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `placa_usuario` VARCHAR(45) NOT NULL,
  `nombre_carro` VARCHAR(45) NOT NULL,
  `credenciales_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_placa_usuario_credenciales1_idx` (`credenciales_id` ASC),
  CONSTRAINT `fk_placa_usuario_credenciales1`
    FOREIGN KEY (`credenciales_id`)
    REFERENCES `apimultas`.`credenciales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
