-- MySQL Script generated by MySQL Workbench
-- mié 23 may 2018 23:06:59 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema apimultas_2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema apimultas_2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apimultas_2` DEFAULT CHARACTER SET utf8 ;
USE `apimultas_2` ;

-- -----------------------------------------------------
-- Table `apimultas_2`.`privilegios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apimultas_2`.`privilegios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `privilegio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `privilegio_UNIQUE` (`privilegio` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apimultas_2`.`credenciales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apimultas_2`.`credenciales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `privilegios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_credenciales_privilegios1_idx` (`privilegios_id` ASC),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC),
  CONSTRAINT `fk_credenciales_privilegios1`
    FOREIGN KEY (`privilegios_id`)
    REFERENCES `apimultas_2`.`privilegios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `apimultas_2`.`placa_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apimultas_2`.`placa_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `placa_usuario` VARCHAR(45) NULL,
  `credenciales_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_placa_usuario_credenciales1_idx` (`credenciales_id` ASC),
  CONSTRAINT `fk_placa_usuario_credenciales1`
    FOREIGN KEY (`credenciales_id`)
    REFERENCES `apimultas_2`.`credenciales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apimultas_2`.`datos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apimultas_2`.`datos` (
  `idmultas` INT NOT NULL AUTO_INCREMENT,
  `no_multa` VARCHAR(15) NOT NULL,
  `placa` VARCHAR(10) NOT NULL,
  `no_tarjeta_cir` VARCHAR(40) NOT NULL,
  `tipo_vehiculo` VARCHAR(40) NOT NULL,
  `marca` VARCHAR(40) NOT NULL,
  `color` VARCHAR(40) NOT NULL,
  `nombres` VARCHAR(60) NOT NULL,
  `apellidos` VARCHAR(60) NOT NULL,
  `no_licencia` VARCHAR(16) NOT NULL,
  `tipo_licencia` VARCHAR(5) NOT NULL,
  `conductor_ausente` VARCHAR(120) NOT NULL,
  `genero` VARCHAR(15) NOT NULL,
  `no_documento_dpi` VARCHAR(16) NOT NULL,
  `domicilio` VARCHAR(120) NOT NULL,
  `lugar_infraccion` VARCHAR(250) NOT NULL,
  `fecha` VARCHAR(10) NOT NULL,
  `articulo_infringido` VARCHAR(250) NOT NULL,
  `base_legal` VARCHAR(250) NOT NULL,
  `monto` DECIMAL NOT NULL,
  `observaciones` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`idmultas`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
